//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop_bbkai
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspis
    {
        public int id_r { get; set; }
        public int id_g { get; set; }
        public int id_c { get; set; }
        public int id_n { get; set; }
        public int id_t { get; set; }
        public string date_r { get; set; }
        public int id_d { get; set; }
        public int id_v { get; set; }
        public string aud_r { get; set; }
        public int zd_r { get; set; }
        public Nullable<int> id_u { get; set; }
    
        public virtual Chet Chet { get; set; }
        public virtual Discs Discs { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Nedeli Nedeli { get; set; }
        public virtual Times Times { get; set; }
        public virtual Users Users { get; set; }
        public virtual Vidi Vidi { get; set; }
    }
}
